#!/usr/bin/env node

console.log('./push')
console.log('  --url http://data.sparkfun.com')
console.log('  --public_key RM1nQNbVRGtaMMgvVz8Y')
console.log('  --private_key lz6d0j7KxPH1VVryqMw5')
console.log('  --field_name temp')
console.log('')
